export default {
    imageCount: 17,
    max: 8,
    spawnDistance: 1800,
    destroyDistance: 3500,
    speedMin: 0.1,
    speedMax: 5,
    rotationSpeedMin: -0.08,
    rotationSpeedMax: 0.08,
    density: 0.1,
    frictionAir: 0,
    restitution: 0.2,
    aimJitter: 600,
    spawnTimeMin: 500,
    spawnTimeMax: 10000,
    spawnChanceMin: 0.5,
    spawnChanceMax: 1,
    spawnCountMin: 1,
    spawnCountMax: 6,
}
