export default {
    bulletsTrail: {
        interval: 0.025,
        size: 10,
        lifetime: 0.25,
        color: '#fff',
        z: -1,
        scaleEnd: 0.25,
        alphaEnd: 0,
        alpha: 0.5,
    },
    meteorsTrail: {
        interval: 0.03,
        lifetime: 0.5,
        color: '#fff',
        z: -1,
        scaleEnd: 0.25,
        alphaEnd: 0,
        alpha: 0.4,
    },
    shot: {
        count: 10,
        sizeMin: 5,
        sizeMax: 12.5,
        speedMin: 80,
        speedMax: 180,
        drag: 4,
        spread: 0.9,
        jitter: 3,
        maxAngular: 8,
        lifetimeMin: 0.5,
        lifetimeMax: 1,
        color: '#fff',
        z: -1,
        offset: 0.75,
        scaleEnd: 0.25,
        alphaEnd: 0,
        alpha: 0.5,
    },
    thrust: {
        interval: 0.03,
        count: 2,
        sizeMin: 6,
        sizeMax: 8,
        speedMin: 30,
        speedMax: 80,
        drag: 2,
        spread: 0.7,
        jitter: 4,
        maxAngular: 6,
        lifetimeMin: 0.2,
        lifetimeMax: 0.4,
        color: '#fff',
        z: -1,
        offset: 0.75,
        scaleEnd: 0.25,
        alphaEnd: 0,
        alpha: 0.5,
    },
    destroy: {
        count: 20,
        sizeMin: 8,
        sizeMax: 16,
        speedMin: 60,
        speedMax: 200,
        drag: 2.5,
        jitter: 6,
        maxAngular: 8,
        lifetimeMin: 0.4,
        lifetimeMax: 0.8,
        color: '#fff',
        z: -1,
        scaleEnd: 0.25,
        alphaEnd: 0,
        alpha: 0.75,
    },
}
