export default {
    speed: {
        label: 'Speed',
        min: 0.002,
        max: 0.005,
        upgrade: 0.0002,
    },
    zoom: {
        label: 'Zoom',
        min: 0.625,
        max: 0.75,
        upgrade: 0.025,
    },
    friction: {
        label: 'Precision',
        min: 0.05,
        max: 0.15,
        upgrade: 0.01,
    },
    bulletSpeed: {
        label: 'Bullet Speed',
        min: 10,
        max: 25,
        upgrade: 1,
    },
    bulletSize: {
        label: 'Bullet Size',
        min: 10,
        max: 30,
        upgrade: 1,
    },
    bulletCount: {
        label: 'Bullet Count',
        weight: 15,
        min: 1,
        max: 5,
        upgrade: 1,
    },
    bulletSpread: {
        label: 'Bullet Precision',
        weight: 60,
        min: 0.5,
        max: 0.15,
        upgrade: -0.05,
    },
    bulletBurstCount: {
        label: 'Bullet Burst Count',
        weight: 10,
        min: 0,
        max: 3,
        upgrade: 1,
    },
    bulletBurstDelay: {
        label: 'Bullet Burst Delay',
        weight: 60,
        min: 0.1,
        max: 0.03,
        upgrade: -0.01,
    },
    bulletLifetime: {
        label: 'Bullet Lifetime',
        min: 3,
        max: 6,
        upgrade: 0.5,
    },
    bulletPiercing: {
        label: 'Bullet Piercing',
        weight: 20,
        min: 0,
        max: 6,
        upgrade: 1,
    },
    shotCooldown: {
        label: 'Fire Rate',
        weight: 40,
        min: 0.375,
        max: 0.05,
        upgrade: -0.025,
    },
    recoil: {
        label: 'Recoil Control',
        weight: 60,
        min: 2.5,
        max: 0,
        upgrade: -0.25,
    },
}
